name: Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Generate XML Documentation
      run: dotnet build examen-si889-2025-ii-u2-nkmelndz.sln --configuration Release /p:DocumentationFile=bin/Release/net9.0/Documentation.xml

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre graphviz

    - name: Generate and convert diagram
      run: |
        mkdir -p diagrams
        # Instalar y usar la herramienta .NET
        dotnet tool install --global PlantUmlClassDiagramGenerator --version 1.4.0
        ~/.dotnet/tools/dotnet-puml-gen examen-si889-2025-ii-u2-nkmelndz.sln diagrams/diagram.puml
        
        # Descargar y usar PlantUML
        wget -O plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2023.12/plantuml-1.2023.12.jar
        java -jar plantuml.jar diagrams/diagram.puml

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: diagrams