name: Publish Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore examen-si889-2025-ii-u2-nkmelndz.sln

    - name: Build application
      run: dotnet build examen-si889-2025-ii-u2-nkmelndz.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test examen-si889-2025-ii-u2-nkmelndz.sln --no-build --configuration Release --collect:"XPlat Code Coverage"

    - name: Publish coverage report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: TestResults/**/*
        retention-days: 30

  # Job separado para el release (opcional)
  release:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    
    steps:
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}