name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore examen-si889-2025-ii-u2-nkmelndz.sln

    - name: Build application
      run: dotnet build examen-si889-2025-ii-u2-nkmelndz.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test examen-si889-2025-ii-u2-nkmelndz.sln --configuration Release --no-build --verbosity normal

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/
        retention-days: 7